// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEthddFMSdVwv2hD37wkccvHhjEx8_2C8',
    appId: '1:427273119688:web:4f7e1b1140cd4720b3c2fd',
    messagingSenderId: '427273119688',
    projectId: 'authenticatorpoint',
    authDomain: 'authenticatorpoint.firebaseapp.com',
    storageBucket: 'authenticatorpoint.firebasestorage.app',
    measurementId: 'G-MRLZ5RCKD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANk9tB_sHtuLLdMhRHDxd7FvNBoj1Bp1I',
    appId: '1:427273119688:android:0d234c59a8ca01a9b3c2fd',
    messagingSenderId: '427273119688',
    projectId: 'authenticatorpoint',
    storageBucket: 'authenticatorpoint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOdEuOXlaRQOh3Rgv2QwiBHwDnXiBuvN4',
    appId: '1:427273119688:ios:7b6c5390f3013f92b3c2fd',
    messagingSenderId: '427273119688',
    projectId: 'authenticatorpoint',
    storageBucket: 'authenticatorpoint.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOdEuOXlaRQOh3Rgv2QwiBHwDnXiBuvN4',
    appId: '1:427273119688:ios:7b6c5390f3013f92b3c2fd',
    messagingSenderId: '427273119688',
    projectId: 'authenticatorpoint',
    storageBucket: 'authenticatorpoint.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEthddFMSdVwv2hD37wkccvHhjEx8_2C8',
    appId: '1:427273119688:web:f715f80805b25691b3c2fd',
    messagingSenderId: '427273119688',
    projectId: 'authenticatorpoint',
    authDomain: 'authenticatorpoint.firebaseapp.com',
    storageBucket: 'authenticatorpoint.firebasestorage.app',
    measurementId: 'G-T0MXQCGS0J',
  );
}
